// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WeatherProducer.AvroSpecific
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AverageWeather : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AverageWeather"",""namespace"":""WeatherProducer.AvroSpecific"",""fields"":[{""name"":""average_temperature"",""type"":""double""},{""name"":""temperature_measurements"",""type"":{""type"":""array"",""items"":""double""}},{""name"":""average_windspeed"",""type"":""double""},{""name"":""windspeed_measurements"",""type"":{""type"":""array"",""items"":""double""}},{""name"":""average_windchill"",""type"":""double""},{""name"":""windchill_measurements"",""type"":{""type"":""array"",""items"":""double""}}]}");
		private double _average_temperature;
		private IList<System.Double> _temperature_measurements;
		private double _average_windspeed;
		private IList<System.Double> _windspeed_measurements;
		private double _average_windchill;
		private IList<System.Double> _windchill_measurements;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AverageWeather._SCHEMA;
			}
		}
		public double average_temperature
		{
			get
			{
				return this._average_temperature;
			}
			set
			{
				this._average_temperature = value;
			}
		}
		public IList<System.Double> temperature_measurements
		{
			get
			{
				return this._temperature_measurements;
			}
			set
			{
				this._temperature_measurements = value;
			}
		}
		public double average_windspeed
		{
			get
			{
				return this._average_windspeed;
			}
			set
			{
				this._average_windspeed = value;
			}
		}
		public IList<System.Double> windspeed_measurements
		{
			get
			{
				return this._windspeed_measurements;
			}
			set
			{
				this._windspeed_measurements = value;
			}
		}
		public double average_windchill
		{
			get
			{
				return this._average_windchill;
			}
			set
			{
				this._average_windchill = value;
			}
		}
		public IList<System.Double> windchill_measurements
		{
			get
			{
				return this._windchill_measurements;
			}
			set
			{
				this._windchill_measurements = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.average_temperature;
			case 1: return this.temperature_measurements;
			case 2: return this.average_windspeed;
			case 3: return this.windspeed_measurements;
			case 4: return this.average_windchill;
			case 5: return this.windchill_measurements;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.average_temperature = (System.Double)fieldValue; break;
			case 1: this.temperature_measurements = (IList<System.Double>)fieldValue; break;
			case 2: this.average_windspeed = (System.Double)fieldValue; break;
			case 3: this.windspeed_measurements = (IList<System.Double>)fieldValue; break;
			case 4: this.average_windchill = (System.Double)fieldValue; break;
			case 5: this.windchill_measurements = (IList<System.Double>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
