// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WeatherApp.Kafka.Schemas.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AggregatedWeather : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AggregatedWeather\",\"namespace\":\"WeatherApp.Kafka.Schemas" +
				".Avro\",\"fields\":[{\"name\":\"AverageTemperature\",\"type\":\"string\"},{\"name\":\"AverageW" +
				"indspeed\",\"type\":\"string\"},{\"name\":\"AverageWindchill\",\"type\":\"string\"}]}");
		private string _AverageTemperature;
		private string _AverageWindspeed;
		private string _AverageWindchill;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AggregatedWeather._SCHEMA;
			}
		}
		public string AverageTemperature
		{
			get
			{
				return this._AverageTemperature;
			}
			set
			{
				this._AverageTemperature = value;
			}
		}
		public string AverageWindspeed
		{
			get
			{
				return this._AverageWindspeed;
			}
			set
			{
				this._AverageWindspeed = value;
			}
		}
		public string AverageWindchill
		{
			get
			{
				return this._AverageWindchill;
			}
			set
			{
				this._AverageWindchill = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.AverageTemperature;
			case 1: return this.AverageWindspeed;
			case 2: return this.AverageWindchill;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.AverageTemperature = (System.String)fieldValue; break;
			case 1: this.AverageWindspeed = (System.String)fieldValue; break;
			case 2: this.AverageWindchill = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
