apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: broker-1
  name: broker-1
spec:
  containers:
    - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_JMX_OPTS
          value: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
        - name: KAFKA_JMX_PORT
          value: "9997"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-1:2181,zookeeper-2:2181
      image: confluentinc/cp-kafka:7.3.0
      name: broker-1
      ports:
        - containerPort: 29092
      resources: {}
  restartPolicy: OnFailure
status: {}
