apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: schemaregistry
  name: schemaregistry
spec:
  containers:
    - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schemaregistry
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: broker-1:9092,broker-2:9092,broker-3:9092
        - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://schemaregistry:8085
      image: confluentinc/cp-schema-registry:7.3.0
      name: schemaregistry
      ports:
        - containerPort: 8085
      resources: {}
  restartPolicy: OnFailure
status: {}
