apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: weather-backend-2
  name: weather-backend-2
spec:
  containers:
    - image: weather-backend-image
      name: weather-backend-2
      imagePullPolicy: Never
      resources: {}
  restartPolicy: OnFailure
status: {}
